config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'download_file', to: 'resources#download_file'

  resources :sessions, only: %i[new create destroy]

  resources :users, except: %i[new] do
    resources :resources do
      member do
        get :download
      end
      resources :file_keys, only: %i[index create show destroy]
    end
  end

  get 'sessions/new'

  root 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/file_key.rb
class FileKey < ApplicationRecord
  has_and_belongs_to_many :resource
end

app/models/resource.rb
class Resource < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :file_key, dependent: :destroy
  has_attached_file :file,
                    resource_type: :raw,
                    path: ":rails_root/public/system/attachment/:style/:id",
                    url: "/system/attachment/:style/:id"

  validates_attachment_presence :file
  validates_attachment_content_type :file, content_type: /.*/
  validates_attachment_size :file, less_than: 30.megabytes
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :resources, dependent: :destroy
  validates :nick_name,
            presence: true,
            uniqueness: true,
            length: { minimum: 5 }

  validates :email,
            presence: true,
            uniqueness: true,
            length: { minimum: 5 },
            format: {
                with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionController::MimeResponds
  protect_from_forgery with: :exception
  
  def current_user
    User.find_by(id: session[:user_id])
  end

  def current_user_resources
    user = User.where(id: session[:user_id]).first
    session[:user_filter] = params[:filter] unless params[:filter].nil?
    filter = session[:user_filter]
    sort = params[:sort] || 'created_at'
    if params[:file_key]
      key_collect =  FileKey.where(file_key: params[:file_key])
      Resource.includes(:file_key).where('file_keys.id' => key_collect)
    elsif user && filter.nil? && sort
      user.resources.order(sort)
    elsif user && sort.nil? && filter && filter.eql?('all')
      user.resources.order(sort)
    elsif user && sort && filter && filter.eql?('all')
      user.resources.order(sort)
    elsif user && sort.nil? && filter
      user.resources.where(resource_type: filter)
    elsif user && sort && filter
      user.resources.where(resource_type: filter).order(sort)
    elsif user
      user.resources.order(sort)
    end
  end

  def resource_file_filter(resource)
    image_extentions_arr = %w[jpg jpeg png svg bmp]
    music_extentions_arr = %w[mp3 wav mpeg]
    archive_extentions_arr = %w[rar zip x-bzip]
    file_name = resource.file_content_type.split('/')[1]
    if file_name.in?(image_extentions_arr)
      resource.file.url
    elsif file_name.in?(music_extentions_arr)
      'MusicFile.png'
    elsif file_name.in?(archive_extentions_arr)
      'ZipFile.png'
    else
      'TextFile.png'
    end
  end

  helper_method :current_user, :resource_file_filter, :current_user_resources
end

app/controllers/file_keys_controller.rb
class FileKeysController < ApplicationController
  skip_before_action :verify_authenticity_token, only: %i[create destroy]

  def index
    @file_keys = FileKey.includes(:resource).where('resources.id' => current_user.resources.ids)
    @resources = Resource.includes(:file_key).where('file_keys.id' => @file_keys.ids)
  end

  def create
    key = generate_file_key
    @resource = current_user.resources.where(id: params[:resource_id].split(','))
    @file_key = FileKey.new(file_key: key)
    if @file_key.save
      p key
      @resource.each do |r|
        r.file_key << @file_key
      end
      respond_to do |format|
        format.js { render file: 'file_keys/create' }
      end
    else
      p 'not saved!'
    end
  end

  def shows
  end

  def destroy
    @file_keys = FileKey.includes(:resource).where('resources.id' => current_user.resources.ids)
    deleted_key = @file_keys.find_by(id: params[:id])
    if deleted_key
      deleted_key.delete
    end
  end

  private

  def generate_file_key
    "#{SecureRandom.hex(9)}t#{Time.now.strftime('%y%m%d%h%m%s')}#{current_user.id}"
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:destroy]
  helper_method :sort_column

  def index
    @resources = current_user.resources
  end

  def show; end

  def new
    @resource = Resource.new
  end

  def create
    @resource = current_user.resources.build(resource_params[:files])
    if current_user.save
      #set_resource_type(@resource)
      redirect_to current_user
    else
      render :new
    end
end

  def destroy
    @resource = current_user.resources.find(params[:id])
    if @resource.destroy
      flash[:notice] = 'Successfully deleted resource'
    else
      flash[:alert] = 'Error deleted resource'
    end
  end

  def download
    @resource = Resource.find_by(id: params[:id])
    send_file @resource.file.path, :type => "application/#{@resource.file_content_type}", :filename => @resource.file_file_name
  end

  private

  def resource_params
    params.require(:resource).permit(files: [:file])
  end

  def sort_column
    params.require(:sorting).permit[:sort] || 'created_at'
  end

  def filter_column
    params.require(:filtering).permit(:filter)
  end

  def set_resource_type(resource)
    image_extentions_arr = %w[jpg jpeg png svg bmp]
    music_extentions_arr = %w[mp3 wav mpeg]
    archive_extentions_arr = %w[rar zip x-bzip]
    video_extentions_arr = %w[mp4]
    file_name = resource.file_content_type.split('/')[1]
    if file_name.in?(image_extentions_arr)
      Resource.where(id: resource.id).update_all(resource_type: 'image')
    elsif file_name.in?(music_extentions_arr)
      Resource.where(id: resource.id).update_all(resource_type: 'audio')
    elsif file_name.in?(video_extentions_arr)
      Resource.where(id: resource.id).update_all(resource_type: 'video')
    elsif file_name.in?(archive_extentions_arr)
      Resource.where(id: resource.id).update_all(resource_type: 'archive')
    else
      Resource.where(id: resource.id).update_all(resource_type: 'file')
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to user_path(session[:user_id]) unless session[:user_id].nil?
  end

  def create
    user = User.find_by_email(params[:email])
    if params[:security_key] && params[:security_key].eql?(user.security_key)
      user.security_key ='0'
      user.save
    end
    if user && user.authenticate(params[:password]) && user.security_key.eql?('0')
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    elsif params[:security_key].nil?
      render 'sessions/new_sk'
    else
      render :new
    end
  end

  def destroy
    session[:user_filter] = nil
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def show
    #sql = "SELECT * from file_keys_resources"
    #result = ActiveRecord::Base.connection.execute(sql)
    #p result.to_a
    #UserMailer.welcome_email(current_user).deliver_later
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.security_key = generate_security_key
      @user.save
      UserMailer.welcome_email(@user).deliver_now
      redirect_to login_path
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end


  def user_params
    params.require(:users).permit(:nick_name, :email, :password, :password_confirmation)
  end

  def generate_security_key
    SecureRandom.hex(6)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_keys_helper.rb
module FileKeysHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/file_keys/create.js.erb
alert('You generate key:<%= @file_key.file_key %>');

app/views/file_keys/destroy.html.erb
<h1>FileKeys#destroy</h1>
<p>Find me in app/views/file_keys/destroy.html.erb</p>

app/views/file_keys/index.html.erb
<div id="filekeybox">
<h2>Your file keys</h2>
<% @file_keys.each do |fk|%>
  <br>
  <div class="filekeyblock">
    <h4>FileKey:</h4><p><%= fk.file_key %></p>
    <h4>Created at:</h4><p><%= fk.created_at %></p>
    <h4>Key for files: </h4><p>
    <% @resources.each do |res|%>
      <%= res.file_file_name %>,
    <% end %></p>

    <button id="<%= fk.id %>" class="file_key_delete">Delete</button>
  </div>
<% end %>
<%= javascript_include_tag 'file_keys'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiskPlace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/resources/_file_content.erb
  <%= javascript_include_tag('file')%>

    <% current_user_resources.each do |resource|%>
    <div class="media", id="<%= resource.id %>">

      <% case resource.resource_type %>
      <% when 'image', 'file', 'archive' %>
        <%=  image_tag(resource_file_filter(resource), class: 'media-object', width: '150px', height: '150px') %>
      <% when 'audio' %>
        <audio  controls>
          <source src="<%= resource.file.url %>"
                  type="<%= resource.file_content_type%>">
          Your browser does not support the audio element.
        </audio>
      <% when 'video' %>
        <video controls controlsList="nodownload">
          <source src="<%= resource.file.url %>"
                  type="<%= resource.file_content_type%>">
          Your browser does not support the video element.
        </video>
      <% end %>
      <div class="clear"></div>
      <div class="firstmedia">
        <h4 class="media-heading">
          <%= File.basename(resource.file_file_name) %>
        </h4>
        <h4 class="media-ext"> <%= File.extname(resource.file_file_name) %></h4>
      </div>
      <div id="<%= resource.id %>" class="secondmedia">
        <% if current_user.resources.ids.include? resource.id %>
          <%= image_tag('deletebtn.png', class: 'destroy') %>
          <%= image_tag('keybtn.png', class: 'generate')%>
        <% end %>
        <%= link_to image_tag('downbtn.png'),download_user_resource_path(:id => resource.id, :user_id => current_user.id),class: 'download'%>
      </div>

    </div>
    <% end %>
  <div class="clear"></div>

app/views/resources/index.js.erb
$(".file_ajax").html("<%= escape_javascript(render('file_content'))%>")

app/views/resources/new.html.erb
<div id="addresource">
<h2>Choose your file</h2>
<%= form_for(:resource, :url => {:controller => 'resources', :action => 'create'},
             html: { multipart: true }) do |f| %>

    <% if @resource.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= "#{pluralize(@resource.errors.count, "error")} prohibited this photo from being saved:" %>
        </h2>
        <ul>
          <% @resource.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>


  <%= file_field(:resource, "files[][file]",:class => 'custom-file-input',:id => 'upload', multiple: true) %>
  <%= f.submit 'Upload Resource',:class => 'button'%>
<% end %>
</div>

app/views/users/_file_content.erb
  <div id="content">
    <div><%= link_to(image_tag('scrollup.png'),{}, id: 'scrollup')%></div>

    <% current_user.resources.each do |resource|%>
    <div class="media", id="<%= resource.id %>">

        <%= link_to image_tag(resource_file_filter(resource), class: 'media-object', width: '150px', height: '150px'),
                    resource_file_filter(resource), target: '_blank' %>
      <div class="clear"></div>
      <h4 class="media-heading">
        <%= File.basename(resource.file_file_name,
                          File.extname(resource.file_file_name))%>
      </h4>   <%= image_tag('deletefile.png', class: 'destroy') %>
    </div>
    <% end %>
  <div class="clear"></div>
  </div>

app/views/users/_footer.html.erb
<div id="footer">
  <div id="footer-top"></div>
  <div id="footer-middle">
    <div id="middle-content">
      <div class="footer-box">
        <div id="magazine">
          <p>Site was founded in 2018.</p>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
        </div>
      </div>
      <div class="footer-box">
        <div id="recent-posts">
          <h3><span>Sponsors</span></h3>
          <ul>
            <li><a href="#">Lorem Ipsum is simply dummy text of the printings</a></li>

          </ul>
        </div>
      </div>
      <div class="footer-box" id="footer-box">
        <div id="archives">
          <h3><span>Links</span></h3>
          <ul>
            <li><a href="#">Lorem Ipsum is simply </a></li>


          </ul>
        </div>
      </div>
      <div class="clear"></div>
    </div>
  </div>
  <div id="footer-bottom">
    <div id="bottom-content">
      <p class="left">Copyright &copy; 2018 <a href="#">Dplace</a> All Rights Reserved.</p>
      <p class="right">Designed &amp; Developed By <a href="#">Tatarskyy Alexander &amp; Nazar Shtereb</a>.</p>
      <div class="clear"></div>
    </div>
  </div>

</div>
<div class="clear"></div>

app/views/users/_form.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
  <title>Log In</title>
  <%= stylesheet_link_tag('styles')%>
</head>
<div class="frozbox">

  <div id="logo">
    <%= image_tag('D.png')%>
  </div>

  <div class ="box">

    <div id="registerbox">

      <%= form_with(model: user, local: true, id: 're') do |form| %>
        <div class="inputBox">
          <%= form.text_field :nick_name, id: :user_nick_name %>
          <%= form.label :nick_name %>
        </div>

        <div class="inputBox">
          <%= form.text_field :email, id: :user_email %>
          <%= form.label :email %>
        </div>

        <div class="inputBox">
          <%= form.password_field :password, id: :user_password %>
          <%= form.label :password %>
        </div>

        <div class="button", id="regbtn">
          <%= form.submit('Register') %>
        </div>

        <%= link_to 'Back', root_path, id: 'back', class: 'linkbtn' %>
      <% end %>

    </div>

  </div>

</div>

app/views/users/_header.html.erb
<div id="header">

  <div id="logo-main"><h1>PLACE</h1><div class="clear"></div></div>
  <div id="avatar"><div id="myDropdown" class="dropdown-content"><%= link_to('Logout', logout_path )%></div>
    <span id="avatarname"><%= current_user.nick_name %></span></div>

  <div class="clear"></div>

</div>

app/views/users/_main_menu.html.erb
<nav class="main-menu" id="left">

  <div class="sidebar">
    <%=image_tag('menulogo.png') %>
    <div id="leftside-navigation" class="nano">
      <ul>

        <li class="sub-menu">
          <%= link_to(image_tag('acc.png') + content_tag(:span,current_user.nick_name),'javascript:void(0);')%>
          <ul>
            <li>  <%= link_to(image_tag('logout.png') + content_tag(:span,'Logout'), logout_path)%>
            </li>

          </ul>
        </li>

         <li class="sub-menu">
          <%= link_to(image_tag('Download.png') + content_tag(:span,'Upload'),new_user_resource_path(current_user.id))%>

          </li>
        <li class="sub-menu">
          <%= link_to(image_tag('Upload.png') + content_tag(:span,'Resources'),'javascript:void(0)')%>
          <ul>
            <li id="all"> <%= link_to(image_tag('allbtn.png') + content_tag(:span,'All'),'javascript:void(0)')%></li>

            <li id="file"> <%= link_to(image_tag('filesbtn.png') + content_tag(:span,'Files'),'javascript:void(0)') %></li>
            <li id="image"> <%= link_to(image_tag('photobtn.png') + content_tag(:span,'Photos'),'javascript:void(0)')%></li>
            <li id="video"> <%= link_to(image_tag('videobtn.png') + content_tag(:span,'Videos'),'javascript:void(0)')%></li>
            <li id="audio"> <%= link_to(image_tag('audiobtn.png') + content_tag(:span,'Audios'),'javascript:void(0)')%></li>
            <li id="archive"> <%= link_to(image_tag('archbtn.png') + content_tag(:span,'Archives'),'javascript:void(0)')%></li>

          </ul>
        </li>
        <li><form><button type="submit" name="" value="find" id="get-files" ><%= image_tag('searchbtn.png')%></button>
          <div class="searchbox"><input id="key-value" type="text" value="" name="" placeholder="KEY" required=""/></div>

        </form></li>




      </ul>
    </div>

  </div>
</nav>

app/views/users/_top_menu.html.erb
<div id="top-menu">
  <div id="inner-menu">
    <ul>

      <div><%= image_tag('scrollup.png',id: 'scrollup')%></div>  <li><%= link_to 'Delete','javascript:void(0);',id: 'delete'  %></li>
      <li><%= link_to 'Select','javascript:void(0);',id: 'select'  %></li>
      <li><%= link_to 'Add key','javascript:void(0);',id: 'share'  %></li>
      <li><%= link_to 'My Keys List', user_resource_file_keys_path(user_id: current_user.id, resource_id: 12)%></li>
      <li>
        <%= radio_button_tag(:toggle, :false, true, id: 'toggle-on', class: 'toggle toggle-left created_at ')%>
        <label for="toggle-on" class="btn ">By date</label>
        <%= radio_button_tag(:toggle, :true, false, id: 'toggle-off', class: 'toggle toggle-right file_file_name')%>
        <label for="toggle-off" class="btn">By name</label></li>

    </ul>

  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
 <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <title>Log In</title>
    <%= stylesheet_link_tag('styles')%>
  </head>

  <div class="frozbox">
    <div id="logo">
      <%= image_tag('D.png')%>
    </div>

    <div class="box">
      <div id="registerbox">
        <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do %>
          <div class="inputBox">
            <%= text_field(:users, :email) %>
            <%= label_tag :email%>
          </div>
          <div class="inputBox">
            <%= text_field(:users, :nick_name) %>
            <%= label_tag :nick_name%>
          </div>
          <div class="inputBox passbox-left">
            <%= password_field(:users, :password)%>
            <%= label_tag :password %>
          </div>
          <div class="inputBox passbox-right">
            <%= password_field(:users, :password_confirmation) %>
            <%= label_tag :password_confirmation %>
          </div>
          <div class="clear"></div>
          <%= submit_tag 'Register', class: 'button', id: 'regbtn' %>
        <% end %>
        <%= link_to('Back', root_path, id: 'back', class: 'linkbtn')%>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<%= render 'main_menu' %>



<%= render 'top_menu' %>

<div id="content" class="file_ajax"> <%= render 'resources/file_content' %></div>

<%= render 'footer' %>